### PR TITLE
Add .liquid extension to html files

### PR DESCRIPTION
**Pull request by AlanGabbianelli**
Add .liquid extension to html files

This has two positive outcomes:
- it makes it clearer that these are files that use the Liquid template 
engine
- it lets text editors highlight the Liquid syntax

### CODE REVIEW

**Comment by AlanGabbianelli** [comment]
I'm not sure, @thomasalanlee. I don't think there's a staging environment or anything like that. Maybe @rubenarakelyan can suggest something?

**Comment by rubenarakelyan** [comment]
You can try building the site locally using the instructions in the README and make sure it builds the HTML files correctly. But this site isn't critical so even if it breaks, we can just revert the change and rebuild it.

**Comment by thomasleese** [comment]
I think we need to set the root page somehow, when I run `bundle exec jekyll serve` in `master` and go to http://localhost:4000/ I see the page, but in this branch, I see a directory listing and I have to manually go to http://localhost:4000/index.html.liquid to see the home page.

**Comment by AlanGabbianelli** [comment]
I think this is related to the `Build Warning: Layout 'page' requested in government-paas.md does not exist.` warning I get when running `bundle exec jekyll serve` in this branch.
Strangely, if I rename the three files to be `<filename>.liquid` instead of `<filename>.html.liquid`, I don't get that warning, but I still see a directory listing.

**Comment by AlanGabbianelli** [comment]
It looks like we may have to drop this. 😐 
- https://github.com/jekyll/jekyll/issues/7030
- https://github.com/jekyll/jekyll/issues/3817

**Pull request closed without merging**
